### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by jsaisagar** [ZhengZerong/MultiviewSMPLifyX#1]
Hi,

Thanks for providing the code. May I know which version you are using. I am getting the below error.

Processing: dataset_example/image_data/rp_dennis_posed_004/color/0306.jpg
Processing: dataset_example/image_data/rp_dennis_posed_004/color/0324.jpg
Processing: dataset_example/image_data/rp_dennis_posed_004/color/0342.jpg
./vposer/models
Found Trained Model: ./vposer/models/snapshots/TR00_E096.pt
Stage:   0%|                                                                                                                                            | 0/4 [00:00<?, ?it/s]
Orientation:   0%|                                                                                                                                      | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/registration/MultiviewSMPLifyX/main.py", line 275, in <module>
    main(**args)
  File "/home/registration/MultiviewSMPLifyX/main.py", line 250, in main
    fit_single_frame(img_list, keypoints_list,
  File "/home/registration/MultiviewSMPLifyX/fit_single_frame.py", line 395, in fit_single_frame
    final_loss_val = monitor.run_fitting(
  File "/home/registration/MultiviewSMPLifyX/fitting.py", line 175, in run_fitting
    loss = optimizer.step(closure)
  File "/home/registration/.conda/envs/pamir_registration/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/registration/MultiviewSMPLifyX/optimizers/lbfgs_ls.py", line 281, in step
    orig_loss = closure()
  File "/home/registration/MultiviewSMPLifyX/fitting.py", line 294, in fitting_func
    body_pose = vposer.decode(
  File "./vposer/models/vposer_smpl.py", line 114, in decode
    if output_type == 'aa': return VPoser.matrot2aa(Xout)
  File "./vposer/models/vposer_smpl.py", line 152, in matrot2aa
    pose = tgm.rotation_matrix_to_angle_axis(homogen_matrot).view(batch_size, 1, -1, 3).contiguous()
  File "/home/registration/.conda/envs/pamir_registration/lib/python3.9/site-packages/torchgeometry/core/conversions.py", line 233, in rotation_matrix_to_angle_axis
    quaternion = rotation_matrix_to_quaternion(rotation_matrix)
  File "/home/registration/.conda/envs/pamir_registration/lib/python3.9/site-packages/torchgeometry/core/conversions.py", line 302, in rotation_matrix_to_quaternion
    mask_c1 = mask_d2 * (1 - mask_d0_d1)
  File "/home/registration/.conda/envs/pamir_registration/lib/python3.9/site-packages/torch/_tensor.py", line 544, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

Thanks for the help,
Sai

**Comment by YHChen0511** [comment]
I have the same problem. How did you solve this problem?

**Comment by yuyingyeh** [comment]
> I have the same problem. How did you solve this problem?

You can use transforms from pytorch3d
`from pytorch3d import transforms`

Replace these two lines
https://github.com/ZhengZerong/MultiviewSMPLifyX/blob/a00c951fef42da353836217b9ba817d366b7cd56/vposer/models/vposer_smpl.py#L151-L152
by
`pose = transforms.matrix_to_axis_angle(pose_matrot.view(-1, 3, 3)).view(batch_size, 1, -1, 3).contiguous()`

and replace this line
https://github.com/ZhengZerong/MultiviewSMPLifyX/blob/a00c951fef42da353836217b9ba817d366b7cd56/vposer/models/vposer_smpl.py#L162
by
`pose_body_matrot = transforms.axis_angle_to_matrix(pose.reshape(-1, 3))[:, :3, :3].contiguous().view(batch_size, 1, -1, 9)`
